services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file: 
      - ./docker/postgres.env
    environment:
      POSTGRES_USER: userpg
      POSTGRES_PASSWORD: passwordpg
      POSTGRES_DB: examtwo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./myapp-back/create.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - ./docker/pgadmin.env
    volumes:
      - ./docker/pgadmin.json:/pgadmin4/config.json
    networks:
      - backend_network

  backend:
    build:
      context: ./myapp-back
      dockerfile: ../docker/dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./myapp-back:/usr/src/app
    env_file:
      - ./docker/backend.env
    depends_on:
      - postgres
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/dockerfile.frontend
    ports:
      - "3001:3000"
    env_file:
      - ./docker/frontend.env
    networks:
      - frontend_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend_network:
  frontend_network: